// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzDfgJTTBgRIgauZ6p8Mr_172HYqo8hS8',
    appId: '1:1082414089886:web:5fa7cc2e272196df7bdd8f',
    messagingSenderId: '1082414089886',
    projectId: 'savepasswordproject',
    authDomain: 'savepasswordproject.firebaseapp.com',
    databaseURL: 'https://savepasswordproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'savepasswordproject.appspot.com',
    measurementId: 'G-9CVXTMVK1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7iWN-sMch1wbT52fjjsETkgd3fRuwKSk',
    appId: '1:1082414089886:android:1568c4e7a2e011f97bdd8f',
    messagingSenderId: '1082414089886',
    projectId: 'savepasswordproject',
    databaseURL: 'https://savepasswordproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'savepasswordproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDArX1Gp4i5XP8mJGmft5kbPXmBpalWejQ',
    appId: '1:1082414089886:ios:41540dcb5f7270d37bdd8f',
    messagingSenderId: '1082414089886',
    projectId: 'savepasswordproject',
    databaseURL: 'https://savepasswordproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'savepasswordproject.appspot.com',
    iosClientId: '1082414089886-ov1esq2hhn6hptop2dthl1qbvqqooruc.apps.googleusercontent.com',
    iosBundleId: 'com.example.savePasswordProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDArX1Gp4i5XP8mJGmft5kbPXmBpalWejQ',
    appId: '1:1082414089886:ios:41540dcb5f7270d37bdd8f',
    messagingSenderId: '1082414089886',
    projectId: 'savepasswordproject',
    databaseURL: 'https://savepasswordproject-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'savepasswordproject.appspot.com',
    iosClientId: '1082414089886-ov1esq2hhn6hptop2dthl1qbvqqooruc.apps.googleusercontent.com',
    iosBundleId: 'com.example.savePasswordProject1',
  );
}
